# Generated by Django 4.1.7 on 2023-04-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rename_book_livre_rename_title_livre_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='archive',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.livre')),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.stock')),
                ('usure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.usure')),
            ],
        ),
        migrations.CreateModel(
            name='emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('adherent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.adherent')),
                ('exemplaire', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.exemplaire')),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.auteur'),
        ),
        migrations.AddField(
            model_name='livre',
            name='editeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backoffice.editeur'),
        ),
        migrations.AddField(
            model_name='livre',
            name='genres',
            field=models.ManyToManyField(default=None, to='backoffice.genre'),
        ),
    ]
